version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python python_flask.py

  draw_map:
    build: .
    volumes:
      - .:/app
    command: python python_draw_map.py
